// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type CloudflareTurntile = {
  /**
   * Turnstile Site Key
   */
  turnstileSiteKey: string;

  /**
   * Turnstile Secret Key
   */
  turnstileSecretKey: string;
};
